### ISSUE TITLE
Category is excluded from export when ID is much lower than parent

### ISSUE THREAD

**Issue by jokeputs** [EmicoEcommerce/Magento2TweakwiseExport-archived#69] opened 2019-05-14 13:51 UTC
This issue is related to #13. When a child category has a parent category with a much higher ID the child category will not be included in the export to Tweakwise. 

The issue will only occur when the difference between the ID's of the child and the parent is high enough that during the export the categories will be processed in two different batches. This happens because the entity_id's used to create the batch are not sorted by category path: https://github.com/EmicoEcommerce/Magento2TweakwiseExport/blob/master/src/Model/Write/EavIterator.php#L273
 
Environment
--
- PHP Version: 7.1
- Magento Version: 2.2.5
- Tweakwise Version: 1.4.8
- Tweakwise Export Version: 1.3.3
- Magento Deploy Mode: production

Steps to reproduce
--
1. In the Magento back-end move a category with a low ID e.g. 120 to a parent category with a much higher ID e.g. 2679
2. Export the data to Tweakwise

Expected result
--
- The child category with the low ID is exported to Tweakwise

Actual result
--
- The child category with the low ID is not exported to Tweakwise

**Comment by edwinljacobs** [comment] 2019-05-15 17:36
Thanks for your report,

I will try to reproduce this on my own installation to verify the issue. As I read it I could change my ```public const ENTITY_BATCH_SIZE = 500;``` to ```1``` for testing?(https://github.com/EmicoEcommerce/Magento2TweakwiseExport/blob/master/src/Model/Write/EavIterator.php#L29)? 

With kind regards, Edwin

**Comment by jokeputs** [comment] 2019-05-17 06:55
Yes, that should work.

**Comment by edwinljacobs** [comment] 2019-05-17 08:43
Ok thanks for the reply I will check it out next week.

**Comment by edwinljacobs** [comment] 2019-05-23 10:16
Hi,

I tested the following scenario: I have a category with id 9 (under store root) called "training", I created a new category called "test" with id 41. And moved the category training under test. So we have a category with 41 as parent and a category with id 9 as child. I changed  
`EavIterator::ENTITY_BATCH_SIZE` to `1`, when exporting both categories are in the export. I added the generated feed as an attachment (could not upload xml so you need to rename it to tweakwise.xml)
[tweakwise.log](https://github.com/EmicoEcommerce/Magento2TweakwiseExport/files/3211467/tweakwise.log)

If you wish I can send you my own database so that you can verify that my test case is correct. 
Since this is not the first time an issue like this has been reported maybe you can send me a stripped version of your database so that I can reproduce and examine the issue? 

With kind regards

**Comment by jokeputs** [comment] 2019-05-28 12:07
I get a different result when I change `EavIterator::ENTITY_BATCH_SIZE` to `1`.

Could you share the `SELECT` queries the iterator creates in `Emico\TweakwiseExport\Model\Write\EavIterator::createSelect` for a batch? 

I've set up a category in my existing category tree:
- Root ID 2
  - Parent ID 2136
    - Child ID 225

I've set the `EavIterator::ENTITY_BATCH_SIZE` to `100`. I use the command `bin/magento tweakwise:export` to create the export.

The child categorie is included in batch 1:
```
SELECT `catalog_category_entity`.`entity_id`, 0 AS `store_id`, 'parent_id' AS `attribute_id`, `catalog_category_entity`.`parent_id` AS `value`, `catalog_category_entity`.`path` FROM `catalog_category_entity` WHERE ((catalog_category_entity.entity_id IN ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '22', '23', '24', '25', '26', '28', '29', '30', '32', '34', '35', '36', '37', '38', '39', '42', '45', '46', '47', '48', '49', '50', '52', '53', '54', '56', '63', '64', '65', '66', '67', '70', '71', '72', '73', '79', '82', '85', '88', '91', '94', '100', '114', '117', '120', '123', '138', '144', '147', '150', '168', '189', '195', '198', '201', '204', '207', '210', '213', '216', '219', '222', '225', '228', '236', '239', '242', '245', '248', '251', '254', '257', '260', '268', '278', '281', '353', '356', '359', '362', '365'))) AND (catalog_category_entity.created_in <= '1556056800') AND (catalog_category_entity.updated_in > '1556056800') UNION SELECT `catalog_category_entity`.`entity_id`, 0 AS `store_id`, 55 AS `attribute_id`, `catalog_category_entity`.`path` AS `value`, `catalog_category_entity`.`path` FROM `catalog_category_entity` WHERE ((catalog_category_entity.entity_id IN ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '22', '23', '24', '25', '26', '28', '29', '30', '32', '34', '35', '36', '37', '38', '39', '42', '45', '46', '47', '48', '49', '50', '52', '53', '54', '56', '63', '64', '65', '66', '67', '70', '71', '72', '73', '79', '82', '85', '88', '91', '94', '100', '114', '117', '120', '123', '138', '144', '147', '150', '168', '189', '195', '198', '201', '204', '207', '210', '213', '216', '219', '222', '225', '228', '236', '239', '242', '245', '248', '251', '254', '257', '260', '268', '278', '281', '353', '356', '359', '362', '365'))) AND (catalog_category_entity.created_in <= '1556056800') AND (catalog_category_entity.updated_in > '1556056800') UNION SELECT `catalog_category_entity`.`entity_id`, 0 AS `store_id`, 65 AS `attribute_id`, `catalog_category_entity`.`level` AS `value`, `catalog_category_entity`.`path` FROM `catalog_category_entity` WHERE ((catalog_category_entity.entity_id IN ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '22', '23', '24', '25', '26', '28', '29', '30', '32', '34', '35', '36', '37', '38', '39', '42', '45', '46', '47', '48', '49', '50', '52', '53', '54', '56', '63', '64', '65', '66', '67', '70', '71', '72', '73', '79', '82', '85', '88', '91', '94', '100', '114', '117', '120', '123', '138', '144', '147', '150', '168', '189', '195', '198', '201', '204', '207', '210', '213', '216', '219', '222', '225', '228', '236', '239', '242', '245', '248', '251', '254', '257', '260', '268', '278', '281', '353', '356', '359', '362', '365'))) AND (catalog_category_entity.created_in <= '1556056800') AND (catalog_category_entity.updated_in > '1556056800') UNION SELECT `catalog_category_entity`.`entity_id`, 0 AS `store_id`, 56 AS `attribute_id`, `catalog_category_entity`.`position` AS `value`, `catalog_category_entity`.`path` FROM `catalog_category_entity` WHERE ((catalog_category_entity.entity_id IN ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '22', '23', '24', '25', '26', '28', '29', '30', '32', '34', '35', '36', '37', '38', '39', '42', '45', '46', '47', '48', '49', '50', '52', '53', '54', '56', '63', '64', '65', '66', '67', '70', '71', '72', '73', '79', '82', '85', '88', '91', '94', '100', '114', '117', '120', '123', '138', '144', '147', '150', '168', '189', '195', '198', '201', '204', '207', '210', '213', '216', '219', '222', '225', '228', '236', '239', '242', '245', '248', '251', '254', '257', '260', '268', '278', '281', '353', '356', '359', '362', '365'))) AND (catalog_category_entity.created_in <= '1556056800') AND (catalog_category_entity.updated_in > '1556056800') UNION SELECT `main_table`.`entity_id`, `attribute_table`.`store_id`, `attribute_table`.`attribute_id`, `attribute_table`.`value`, `main_table`.`path` FROM `catalog_category_entity_varchar` AS `attribute_table`
 INNER JOIN `catalog_category_entity` AS `main_table` ON attribute_table.row_id = main_table.row_id AND (main_table.created_in <= '1556056800' AND main_table.updated_in > '1556056800') WHERE (attribute_id IN (45)) AND (store_id = 0 OR store_id = 1) AND (entity_id IN ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '22', '23', '24', '25', '26', '28', '29', '30', '32', '34', '35', '36', '37', '38', '39', '42', '45', '46', '47', '48', '49', '50', '52', '53', '54', '56', '63', '64', '65', '66', '67', '70', '71', '72', '73', '79', '82', '85', '88', '91', '94', '100', '114', '117', '120', '123', '138', '144', '147', '150', '168', '189', '195', '198', '201', '204', '207', '210', '213', '216', '219', '222', '225', '228', '236', '239', '242', '245', '248', '251', '254', '257', '260', '268', '278', '281', '353', '356', '359', '362', '365')) UNION SELECT `main_table`.`entity_id`, `attribute_table`.`store_id`, `attribute_table`.`attribute_id`, `attribute_table`.`value`, `main_table`.`path` FROM `catalog_category_entity_int` AS `attribute_table`
 INNER JOIN `catalog_category_entity` AS `main_table` ON attribute_table.row_id = main_table.row_id AND (main_table.created_in <= '1556056800' AND main_table.updated_in > '1556056800') WHERE (attribute_id IN (46)) AND (store_id = 0 OR store_id = 1) AND (entity_id IN ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '22', '23', '24', '25', '26', '28', '29', '30', '32', '34', '35', '36', '37', '38', '39', '42', '45', '46', '47', '48', '49', '50', '52', '53', '54', '56', '63', '64', '65', '66', '67', '70', '71', '72', '73', '79', '82', '85', '88', '91', '94', '100', '114', '117', '120', '123', '138', '144', '147', '150', '168', '189', '195', '198', '201', '204', '207', '210', '213', '216', '219', '222', '225', '228', '236', '239', '242', '245', '248', '251', '254', '257', '260', '268', '278', '281', '353', '356', '359', '362', '365')) ORDER BY `path` ASC, `entity_id` ASC, `store_id` ASC
```

The parent is only included the batch 5:
```
SELECT `catalog_category_entity`.`entity_id`, 0 AS `store_id`, 'parent_id' AS `attribute_id`, `catalog_category_entity`.`parent_id` AS `value`, `catalog_category_entity`.`path` FROM `catalog_category_entity` WHERE ((catalog_category_entity.entity_id IN ('2034', '2037', '2040', '2043', '2046', '2049', '2052', '2055', '2058', '2061', '2064', '2067', '2070', '2073', '2079', '2082', '2085', '2088', '2091', '2094', '2097', '2100', '2106', '2112', '2118', '2121', '2124', '2127', '2130', '2133', '2136', '2142', '2145', '2148', '2151', '2154', '2157', '2160', '2163', '2166', '2169', '2172', '2175', '2181', '2184', '2187', '2190', '2193', '2196', '2199', '2205', '2208', '2211', '2214', '2217', '2220', '2223', '2226', '2229', '2232', '2235', '2241', '2247', '2253', '2256', '2259', '2262', '2265', '2268', '2271', '2274', '2277', '2280', '2283', '2286', '2289', '2292', '2295', '2298', '2301', '2304', '2307', '2310', '2313', '2319', '2322', '2325', '2328', '2334', '2340', '2343', '2346', '2349', '2352', '2355', '2358', '2367', '2373', '2376', '2379'))) AND (catalog_category_entity.created_in <= '1556056800') AND (catalog_category_entity.updated_in > '1556056800') UNION SELECT `catalog_category_entity`.`entity_id`, 0 AS `store_id`, 55 AS `attribute_id`, `catalog_category_entity`.`path` AS `value`, `catalog_category_entity`.`path` FROM `catalog_category_entity` WHERE ((catalog_category_entity.entity_id IN ('2034', '2037', '2040', '2043', '2046', '2049', '2052', '2055', '2058', '2061', '2064', '2067', '2070', '2073', '2079', '2082', '2085', '2088', '2091', '2094', '2097', '2100', '2106', '2112', '2118', '2121', '2124', '2127', '2130', '2133', '2136', '2142', '2145', '2148', '2151', '2154', '2157', '2160', '2163', '2166', '2169', '2172', '2175', '2181', '2184', '2187', '2190', '2193', '2196', '2199', '2205', '2208', '2211', '2214', '2217', '2220', '2223', '2226', '2229', '2232', '2235', '2241', '2247', '2253', '2256', '2259', '2262', '2265', '2268', '2271', '2274', '2277', '2280', '2283', '2286', '2289', '2292', '2295', '2298', '2301', '2304', '2307', '2310', '2313', '2319', '2322', '2325', '2328', '2334', '2340', '2343', '2346', '2349', '2352', '2355', '2358', '2367', '2373', '2376', '2379'))) AND (catalog_category_entity.created_in <= '1556056800') AND (catalog_category_entity.updated_in > '1556056800') UNION SELECT `catalog_category_entity`.`entity_id`, 0 AS `store_id`, 65 AS `attribute_id`, `catalog_category_entity`.`level` AS `value`, `catalog_category_entity`.`path` FROM `catalog_category_entity` WHERE ((catalog_category_entity.entity_id IN ('2034', '2037', '2040', '2043', '2046', '2049', '2052', '2055', '2058', '2061', '2064', '2067', '2070', '2073', '2079', '2082', '2085', '2088', '2091', '2094', '2097', '2100', '2106', '2112', '2118', '2121', '2124', '2127', '2130', '2133', '2136', '2142', '2145', '2148', '2151', '2154', '2157', '2160', '2163', '2166', '2169', '2172', '2175', '2181', '2184', '2187', '2190', '2193', '2196', '2199', '2205', '2208', '2211', '2214', '2217', '2220', '2223', '2226', '2229', '2232', '2235', '2241', '2247', '2253', '2256', '2259', '2262', '2265', '2268', '2271', '2274', '2277', '2280', '2283', '2286', '2289', '2292', '2295', '2298', '2301', '2304', '2307', '2310', '2313', '2319', '2322', '2325', '2328', '2334', '2340', '2343', '2346', '2349', '2352', '2355', '2358', '2367', '2373', '2376', '2379'))) AND (catalog_category_entity.created_in <= '1556056800') AND (catalog_category_entity.updated_in > '1556056800') UNION SELECT `catalog_category_entity`.`entity_id`, 0 AS `store_id`, 56 AS `attribute_id`, `catalog_category_entity`.`position` AS `value`, `catalog_category_entity`.`path` FROM `catalog_category_entity` WHERE ((catalog_category_entity.entity_id IN ('2034', '2037', '2040', '2043', '2046', '2049', '2052', '2055', '2058', '2061', '2064', '2067', '2070', '2073', '2079', '2082', '2085', '2088', '2091', '2094', '2097', '2100', '2106', '2112', '2118', '2121', '2124', '2127', '2130', '2133', '2136', '2142', '2145', '2148', '2151', '2154', '2157', '2160', '2163', '2166', '2169', '2172', '2175', '2181', '2184', '2187', '2190', '2193', '2196', '2199', '2205', '2208', '2211', '2214', '2217', '2220', '2223', '2226', '2229', '2232', '2235', '2241', '2247', '2253', '2256', '2259', '2262', '2265', '2268', '2271', '2274', '2277', '2280', '2283', '2286', '2289', '2292', '2295', '2298', '2301', '2304', '2307', '2310', '2313', '2319', '2322', '2325', '2328', '2334', '2340', '2343', '2346', '2349', '2352', '2355', '2358', '2367', '2373', '2376', '2379'))) AND (catalog_category_entity.created_in <= '1556056800') AND (catalog_category_entity.updated_in > '1556056800') UNION SELECT `main_table`.`entity_id`, `attribute_table`.`store_id`, `attribute_table`.`attribute_id`, `attribute_table`.`value`, `main_table`.`path` FROM `catalog_category_entity_varchar` AS `attribute_table`
 INNER JOIN `catalog_category_entity` AS `main_table` ON attribute_table.row_id = main_table.row_id AND (main_table.created_in <= '1556056800' AND main_table.updated_in > '1556056800') WHERE (attribute_id IN (45)) AND (store_id = 0 OR store_id = 1) AND (entity_id IN ('2034', '2037', '2040', '2043', '2046', '2049', '2052', '2055', '2058', '2061', '2064', '2067', '2070', '2073', '2079', '2082', '2085', '2088', '2091', '2094', '2097', '2100', '2106', '2112', '2118', '2121', '2124', '2127', '2130', '2133', '2136', '2142', '2145', '2148', '2151', '2154', '2157', '2160', '2163', '2166', '2169', '2172', '2175', '2181', '2184', '2187', '2190', '2193', '2196', '2199', '2205', '2208', '2211', '2214', '2217', '2220', '2223', '2226', '2229', '2232', '2235', '2241', '2247', '2253', '2256', '2259', '2262', '2265', '2268', '2271', '2274', '2277', '2280', '2283', '2286', '2289', '2292', '2295', '2298', '2301', '2304', '2307', '2310', '2313', '2319', '2322', '2325', '2328', '2334', '2340', '2343', '2346', '2349', '2352', '2355', '2358', '2367', '2373', '2376', '2379')) UNION SELECT `main_table`.`entity_id`, `attribute_table`.`store_id`, `attribute_table`.`attribute_id`, `attribute_table`.`value`, `main_table`.`path` FROM `catalog_category_entity_int` AS `attribute_table`
 INNER JOIN `catalog_category_entity` AS `main_table` ON attribute_table.row_id = main_table.row_id AND (main_table.created_in <= '1556056800' AND main_table.updated_in > '1556056800') WHERE (attribute_id IN (46)) AND (store_id = 0 OR store_id = 1) AND (entity_id IN ('2034', '2037', '2040', '2043', '2046', '2049', '2052', '2055', '2058', '2061', '2064', '2067', '2070', '2073', '2079', '2082', '2085', '2088', '2091', '2094', '2097', '2100', '2106', '2112', '2118', '2121', '2124', '2127', '2130', '2133', '2136', '2142', '2145', '2148', '2151', '2154', '2157', '2160', '2163', '2166', '2169', '2172', '2175', '2181', '2184', '2187', '2190', '2193', '2196', '2199', '2205', '2208', '2211', '2214', '2217', '2220', '2223', '2226', '2229', '2232', '2235', '2241', '2247', '2253', '2256', '2259', '2262', '2265', '2268', '2271', '2274', '2277', '2280', '2283', '2286', '2289', '2292', '2295', '2298', '2301', '2304', '2307', '2310', '2313', '2319', '2322', '2325', '2328', '2334', '2340', '2343', '2346', '2349', '2352', '2355', '2358', '2367', '2373', '2376', '2379')) ORDER BY `path` ASC, `entity_id` ASC, `store_id` ASC
```

Because of this check https://github.com/EmicoEcommerce/Magento2TweakwiseExport/blob/master/src/Model/Write/Categories.php#L135 the child category is not included in my export.

**Comment by edwinljacobs** [comment] 2019-06-05 17:01
Hi,

Though I could not reproduce this I tried to come op with a fix in branch: https://github.com/EmicoEcommerce/Magento2TweakwiseExport/tree/issue/100701-child-products-out-of-batch. I also created a pending pull request: https://github.com/EmicoEcommerce/Magento2TweakwiseExport/pull/71

Could check that pull request and test if that branch fixes your issue?
In short we added an order to the batch, first on level so that all parents are exported first and then on path.

WIth kind regards

**Comment by edwinljacobs** [comment] 2019-06-05 17:05
Apparently I posted the wrong branch it should be this branch: https://github.com/EmicoEcommerce/Magento2TweakwiseExport/tree/issue/107645-category-excluded-when-out-of-batch

**Comment by jokeputs** [comment] 2019-06-06 07:33
Thanks! I'll try it and I will let you know if it works.

**Comment by jokeputs** [comment] 2019-06-06 07:59
It works! 
How soon will this be added to a new release?

**Comment by edwinljacobs** [comment] 2019-06-06 10:20
Nice to hear :) 

Most likely the release will be next wednesday. It could be that we will refactor the batching process away from the eavIterator since that class is starting to be responsible for too many things. It would require some code adjustments but I think I'll get that done before wednesday next week.

With kind regards

**Comment by edwinljacobs** [comment] 2019-06-12 12:25
Hello,

This has been released in https://github.com/EmicoEcommerce/Magento2TweakwiseExport/releases/tag/v1.3.7

With kind regards

**Closed as completed by edwinljacobs** 2019-06-12 12:25 UTC
