### ISSUE TITLE
Duplicate feed data

### ISSUE THREAD

**Issue by VesnaS** [EmicoEcommerce/Magento2TweakwiseExport-archived#24] opened 2017-11-02 12:02 UTC
Extension version: latest release
Magento version: 2.1.6
PHP 7

Hi,
We upgraded extension to the latest version.
When we generate the feed from the command line we can import it in Tweakwise navigator interface without any issues.

When we enable "Export in Real Time" option, and run task from navigator panel, we get the following error:
"Something went wrong while executing this task. Please contact Tweakwise Support."

When I download this file, the feed is twice the size of the one generated from CLI, and it has all the data duplicated.

I found this closed issue that is very similar to the one we are experiencing: https://github.com/EmicoEcommerce/Magento2TweakwiseExport/issues/3

**Comment by Fgruntjes** [comment] 2017-11-09 04:42
Hello,

Thank you for the issue. We will have a closer look with the "real time" setting.

**Comment by Fgruntjes** [comment] 2017-11-09 05:30
We checked this again but the feed is generated exactly the same when using the real time setting. Also looking the timestamp part in the feed we see that the feed was generated again.

Judging from the code I really can't think of a way that this would have happened. Could you try to make your situation reproducible with a clean Magento installation with sample data and provide us with the exact steps.

Other then that I suggest not using the realtime feature any way. This feature really only should be used when you are dealing with small catalogs.

**Comment by Fgruntjes** [comment] 2017-12-14 01:09
Since no extra information is provided we close the issue.

**Closed as completed by Fgruntjes** 2017-12-14 01:09 UTC
Labels: bug, can't reproduce
